name: Release the application
on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Input the release tag'
        required: true
        type: string

env:
  RELEASE_TAG: ${{ github.event.inputs.releaseTag }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: Download Daemon Release
        uses: robinraju/release-downloader@v1.10
        with:
          repository: 'ebsoftwareservices/econnector-daemon'
          latest: true
          fileName: 'econnector-daemon.zip'
          out-file-path: files
          extract: true
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Download UI Release
        uses: robinraju/release-downloader@v1.10
        with:
          repository: 'ebsoftwareservices/econnector-ui'
          latest: true
          fileName: 'econnector-ui.zip'
          out-file-path: files
          extract: true
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Build Zip File 
        run: |
          rm -rf files/econnector-*.zip .git* *.md upgrade.bat
          zip -r econnector-installation.zip .

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: Release ${{ env.RELEASE_TAG }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./econnector-installation.zip
          asset_name: econnector-installation.zip
          asset_content_type: application/zip
